// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UninunezRNIBackend.Data;

#nullable disable

namespace UninunezRNIBackend.API.Migrations
{
    [DbContext(typeof(UninunezRNIDbContext))]
    partial class UninunezRNIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UninunezRNIBackend.Models.Domain.AgreementRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AttachedDocumentsPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "documentosAdjuntosRuta");

                    b.Property<string>("CommitteeComments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasAnnotation("Relational:JsonPropertyName", "comentariosComite");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "contactoEmail");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "contactoNombre");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasAnnotation("Relational:JsonPropertyName", "contactoTelefono");

                    b.Property<string>("ContactPosition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "contactoCargo");

                    b.Property<string>("InternalObservations")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasAnnotation("Relational:JsonPropertyName", "observacionesInternas");

                    b.Property<double?>("MembershipPaymentAmount")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "valorPagoMembresia");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasAnnotation("Relational:JsonPropertyName", "observaciones");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "proposerPosition");

                    b.Property<string>("ProposedOrganization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasAnnotation("Relational:JsonPropertyName", "organizacionPropuesta");

                    b.Property<string>("ProposerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "proposerEmail");

                    b.Property<string>("ProposerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "proposerName");

                    b.Property<string>("ProposerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasAnnotation("Relational:JsonPropertyName", "proposerPhone");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "fechaSolicitud");

                    b.Property<bool>("RequiresMembershipPayment")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "requierePagoMembresia");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "proposerRole");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "estadoSolicitud");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "requestType");

                    b.HasKey("Id");

                    b.ToTable("AgreementRequests");
                });

            modelBuilder.Entity("UninunezRNIBackend.Models.Domain.AgreementRequestStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgreementRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgreementRequestId");

                    b.ToTable("AgreementRequestStatusHistories");
                });

            modelBuilder.Entity("UninunezRNIBackend.Models.Domain.AgreementRequestStatusHistory", b =>
                {
                    b.HasOne("UninunezRNIBackend.Models.Domain.AgreementRequest", "AgreementRequest")
                        .WithMany("StatusHistory")
                        .HasForeignKey("AgreementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgreementRequest");
                });

            modelBuilder.Entity("UninunezRNIBackend.Models.Domain.AgreementRequest", b =>
                {
                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
